name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:

  # ─── Job 1: Build & Test ──────────────────────────────────────
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: Demo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven                  #

      - name: Wait for MySQL to be Ready
        run: sleep 20                   #

      - name: Run Tests with Coverage
        run: mvn clean test jacoco:report
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/Demo
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Build Using Maven (skip tests — already ran)
        run: mvn clean install -DskipTests #creates jar if all above steps are good

  # ─── Job 2: Build & Push Docker Image ────────────────────────
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test            # only runs if Job 1 passes ✅

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-demo:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-demo:latest